-- ============================================================
-- Rientra@ Step 1 — Schema PostgreSQL minimale
-- Esegui con:
--   psql -U postgres -d rientra_db -f sql/setup.sql
-- ============================================================

-- Pulisce le tabelle se esistono già (utile per rieseguire)
DROP TABLE IF EXISTS job_descriptor    CASCADE;
DROP TABLE IF EXISTS health_condition_code CASCADE;
DROP TABLE IF EXISTS job               CASCADE;
DROP TABLE IF EXISTS health_condition  CASCADE;
DROP TABLE IF EXISTS icf_code          CASCADE;
DROP TABLE IF EXISTS wheelchair_user   CASCADE;

-- ─────────────────────────────────────────────
-- TABELLE
-- ─────────────────────────────────────────────

CREATE TABLE wheelchair_user (
    id          SERIAL PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    birth_year  INTEGER,
    gender      CHAR(1),
    email       VARCHAR(200)
);

CREATE TABLE icf_code (
    code        VARCHAR(20)  PRIMARY KEY,
    component   CHAR(1)      NOT NULL,   -- b, s, d, e
    name        VARCHAR(300) NOT NULL,
    description TEXT
);

CREATE TABLE health_condition (
    id          SERIAL PRIMARY KEY,
    worker_id   INTEGER NOT NULL REFERENCES wheelchair_user(id),
    assessed_on DATE    NOT NULL,
    notes       TEXT
);

CREATE TABLE health_condition_code (
    id           SERIAL  PRIMARY KEY,
    condition_id INTEGER NOT NULL REFERENCES health_condition(id),
    icf_code     VARCHAR(20) NOT NULL REFERENCES icf_code(code),
    qualifier_1  INTEGER,   -- magnitudine compromissione (0-4)
    qualifier_2  INTEGER    -- capacità senza assistenza (solo per d)
);

CREATE TABLE job (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(300) NOT NULL,   -- nome nel DB istituzionale
    description TEXT,
    onet_code   VARCHAR(20)              -- codice O*NET (ground truth)
);

CREATE TABLE job_descriptor (
    id               SERIAL  PRIMARY KEY,
    job_id           INTEGER NOT NULL REFERENCES job(id),
    descriptor_name  VARCHAR(200) NOT NULL,
    category         VARCHAR(50),         -- 'Skill' o 'Ability'
    importance_score INTEGER,
    importance_anchor INTEGER
);

-- ─────────────────────────────────────────────
-- DATI DI ESEMPIO
-- ─────────────────────────────────────────────

-- Wheelchair Users (basati sui TestHC del paper)
INSERT INTO wheelchair_user (first_name, last_name, birth_year, gender, email) VALUES
('Marco',     'Bianchi',  1975, 'M', 'marco.bianchi@example.it'),
('Luca',      'Ferretti', 1982, 'M', 'luca.ferretti@example.it'),
('Francesca', 'Neri',     1990, 'F', 'francesca.neri@example.it'),
('Antonio',   'Russo',    1979, 'M', 'antonio.russo@example.it');

-- Codici ICF (sottoinsieme rilevante)
INSERT INTO icf_code (code, component, name, description) VALUES
('b130',  'b', 'Energy and drive functions',           'General mental functions of physiological mechanisms.'),
('b140',  'b', 'Attention functions',                  'Mental functions of focusing on an external stimulus.'),
('b1400', 'b', 'Sustaining attention',                 'Mental functions that produce concentration.'),
('b1401', 'b', 'Shifting attention',                   'Mental functions that permit refocusing concentration.'),
('b147',  'b', 'Psychomotor functions',                'Specific mental functions of control over motor events.'),
('b1478', 'b', 'Reaction time',                        'Time elapsed between stimulation and response.'),
('b710',  'b', 'Mobility of joint functions',          'Functions of the range and ease of movement of a joint.'),
('b730',  'b', 'Muscle power functions',               'Functions related to the force generated by muscles.'),
('b7305', 'b', 'Power of muscles of the trunk',        'Force generated by trunk muscles.'),
('b7306', 'b', 'Power of all muscles of the body',     'Force generated by all body muscles.'),
('b735',  'b', 'Muscle tone functions',                'Tension present in resting muscles.'),
('b760',  'b', 'Control of voluntary movement',        'Control over and coordination of voluntary movements.'),
('b7602', 'b', 'Coordination of voluntary movements',  'Coordination of simple and complex voluntary movements.'),
('b7603', 'b', 'Supportive functions of arm or leg',   'Control for bearing weight of body or object.'),
('b770',  'b', 'Gait pattern functions',               'Movement patterns associated with walking.'),
('b789',  'b', 'Dynamic flexibility',                  'Ability to make rapid repeated flexing movements.'),
('d160',  'd', 'Focusing attention',                   'Intentionally focusing on specific stimuli.'),
('d170',  'd', 'Writing',                              'Using symbols to convey information.'),
('d430',  'd', 'Lifting and carrying objects',         'Raising up an object or taking it from one place to another.'),
('d440',  'd', 'Fine hand use',                        'Coordinated actions of handling objects with fingers.'),
('d445',  'd', 'Hand and arm use',                     'Coordinated actions to move objects using hands and arms.'),
('d450',  'd', 'Walking',                              'Moving along a surface on foot, step by step.'),
('d455',  'd', 'Moving around',                        'Moving the whole body by means other than walking.');

-- Condizioni di salute
INSERT INTO health_condition (worker_id, assessed_on, notes) VALUES
(1, '2024-01-10', 'TBI con paralisi completa arti inferiori. Problemi cognitivi aggravati. Depressione.'),
(2, '2024-01-15', 'Tetraplegia incompleta post SCI. Paralisi arti inferiori. Limitazioni tronco e arti superiori.'),
(3, '2024-02-01', 'Paraplegia post TBI. Lievi deficit cognitivi. Buona funzionalità arti superiori.'),
(4, '2024-02-10', 'Paraplegia post SCI. Dolore cronico arti superiori. Lievi deficit cognitivi e visivi.');

-- Codici ICF per WU 1 (TestHC1: TBI grave)
INSERT INTO health_condition_code (condition_id, icf_code, qualifier_1) VALUES
(1, 'b130',  2), (1, 'b140',  1), (1, 'b1400', 2),
(1, 'b1401', 2), (1, 'b147',  3), (1, 'b1478', 2),
(1, 'b710',  3), (1, 'b730',  2), (1, 'b7305', 1),
(1, 'b7306', 2), (1, 'b735',  2), (1, 'b760',  2),
(1, 'b7602', 1), (1, 'b770',  4), (1, 'd450',  4), (1, 'd455',  4);

-- Codici ICF per WU 2 (TestHC2: SCI tetraplegia)
INSERT INTO health_condition_code (condition_id, icf_code, qualifier_1) VALUES
(2, 'b1401', 1), (2, 'b1478', 2), (2, 'b710',  2),
(2, 'b730',  2), (2, 'b7305', 2), (2, 'b7306', 2),
(2, 'b735',  2), (2, 'b760',  2), (2, 'b7602', 2),
(2, 'b7603', 2), (2, 'b770',  3), (2, 'b789',  3),
(2, 'd430',  2), (2, 'd440',  1), (2, 'd445',  2),
(2, 'd450',  4), (2, 'd455',  4);

-- Codici ICF per WU 3 (TestHC3: paraplegia lieve)
INSERT INTO health_condition_code (condition_id, icf_code, qualifier_1) VALUES
(3, 'b1400', 1), (3, 'b1401', 1), (3, 'b710',  1),
(3, 'b730',  1), (3, 'b7305', 1), (3, 'b7306', 2),
(3, 'b735',  1), (3, 'b760',  1), (3, 'b7602', 1),
(3, 'b7603', 1), (3, 'd160',  1), (3, 'd170',  1),
(3, 'd450',  4), (3, 'd455',  4);

-- Codici ICF per WU 4 (TestHC4: paraplegia + dolore)
INSERT INTO health_condition_code (condition_id, icf_code, qualifier_1) VALUES
(4, 'b1401', 1), (4, 'b710',  2), (4, 'b730',  1),
(4, 'b7305', 1), (4, 'b7306', 1), (4, 'b735',  1),
(4, 'b760',  1), (4, 'b7602', 1), (4, 'b7603', 2),
(4, 'b770',  1), (4, 'b789',  2), (4, 'd160',  1),
(4, 'd450',  4), (4, 'd455',  4);

-- Professioni (nomi volutamente diversi da O*NET per simulare il mismatch)
INSERT INTO job (name, description, onet_code) VALUES
('Manager of the digital archive',
 'Evaluate and oversee preservation of permanent records and historically significant documents.',
 '25-4011.00'),

('Office document manager',
 'Organize, manage and retrieve office documents and correspondence.',
 '43-4071.00'),

('Reception and customer service operator',
 'Greet visitors, answer calls, provide information and manage bookings.',
 '43-4171.00'),

('Data entry and document processing specialist',
 'Input and verify data using computer systems and office software.',
 '43-9022.00'),

('Outdoor maintenance worker',
 'Maintain gardens, green areas and outdoor spaces.',
 '37-3011.00');

-- Descrittori O*NET per i primi due lavori
INSERT INTO job_descriptor (job_id, descriptor_name, category, importance_score, importance_anchor) VALUES
(1, 'Reading Comprehension', 'Skill',   75, 3),
(1, 'Writing',               'Skill',   72, 2),
(1, 'Active Listening',      'Skill',   68, 2),
(1, 'Information Ordering',  'Ability', 78, 3),
(1, 'Written Comprehension', 'Ability', 81, 3),

(2, 'Active Listening',      'Skill',   60, 2),
(2, 'Speaking',              'Skill',   55, 2),
(2, 'Information Ordering',  'Ability', 65, 2),
(2, 'Near Vision',           'Ability', 58, 2);
